{"nbformat":4,"nbformat_minor":0,"metadata":{"colab":{"provenance":[]},"kernelspec":{"name":"python3","display_name":"Python 3"}},"cells":[{"cell_type":"markdown","metadata":{"id":"Tv9mRq_bZhYC"},"source":["# Exception Handling:\n","\n","---\n","\n","When an error occurs, or exception as we call it, Python will normally stop and generate an error message.\n","\n","These exceptions can be handled using the try statement:"]},{"cell_type":"code","metadata":{"id":"7kdN7FcmZfKf","colab":{"base_uri":"https://localhost:8080/"},"outputId":"afc41076-82fb-462f-85b4-76deaf9db399","executionInfo":{"status":"ok","timestamp":1752243986057,"user_tz":-330,"elapsed":47,"user":{"displayName":"udaysudheer","userId":"14541240013211259843"}}},"source":["# The try block will generate an exception, because x is not defined:\n","\n","try:\n","  print(x)\n","except:\n","  print(\"An exception occurred\")"],"execution_count":null,"outputs":[{"output_type":"stream","name":"stdout","text":["An exception occurred\n"]}]},{"cell_type":"markdown","metadata":{"id":"GxRmVhscZ7BY"},"source":["Since the try block raises an error, the except block will be executed."]},{"cell_type":"markdown","metadata":{"id":"40KGJl-TaALn"},"source":["## Many Exceptions\n","\n","---\n","\n","\n","You can define as many exception blocks as you want, e.g. if you want to execute a special block of code for a special kind of error:"]},{"cell_type":"code","metadata":{"id":"tWWEUpplZx72","colab":{"base_uri":"https://localhost:8080/"},"outputId":"3160b66a-784b-4f6e-933a-380a9d02c1b6","executionInfo":{"status":"ok","timestamp":1752287732912,"user_tz":-330,"elapsed":19,"user":{"displayName":"udaysudheer","userId":"14541240013211259843"}}},"source":["# Print one message if the try block raises a NameError and another for other errors:\n","\n","try:\n","  print(x)\n","except NameError:\n","  print(\"Variable x is not defined\")\n","except:\n","  print(\"Something else went wrong\")"],"execution_count":1,"outputs":[{"output_type":"stream","name":"stdout","text":["Variable x is not defined\n"]}]},{"cell_type":"markdown","metadata":{"id":"rj5Z2JTLaK1G"},"source":["## Else\n","You can use the else keyword to define a block of code to be executed if no errors were raised:\n","\n","Example\n","In this example, the try block does not generate any error:"]},{"cell_type":"code","metadata":{"id":"-9lLpeN8aF3q","colab":{"base_uri":"https://localhost:8080/"},"outputId":"625e13b7-d8e3-4d1f-930a-e44bfe29fe8e","executionInfo":{"status":"ok","timestamp":1752288740457,"user_tz":-330,"elapsed":45,"user":{"displayName":"udaysudheer","userId":"14541240013211259843"}}},"source":["try:\n","  print(\"Hello\");\n","except:\n","  print(\"Something went wrong\")\n","else:\n","  print(\"Nothing went wrong\")"],"execution_count":12,"outputs":[{"output_type":"stream","name":"stdout","text":["Hello\n","Nothing went wrong\n"]}]},{"cell_type":"markdown","metadata":{"id":"IKVwA-ZJaS6x"},"source":["## Finally\n","The finally block, if specified, will be executed regardless if the try block raises an error or not.\n","\n","Example\n"]},{"cell_type":"code","metadata":{"id":"1UZJLGYTaPWU","colab":{"base_uri":"https://localhost:8080/","height":51},"outputId":"7fcf1999-9e13-462d-c0ea-5dd9bd9be20d"},"source":["try:\n","  print(x)\n","except:\n","  print(\"Something went wrong\")\n","finally:\n","  print(\"The 'try except' is finished\")"],"execution_count":null,"outputs":[{"output_type":"stream","text":["Something went wrong\n","The 'try except' is finished\n"],"name":"stdout"}]},{"cell_type":"code","metadata":{"id":"035jIFc_aVAJ","executionInfo":{"status":"ok","timestamp":1752288124048,"user_tz":-330,"elapsed":51,"user":{"displayName":"udaysudheer","userId":"14541240013211259843"}},"colab":{"base_uri":"https://localhost:8080/"},"outputId":"2900bae2-4c4a-4c5e-a4c3-7753fd00af4e"},"source":["#This can be useful to close objects and clean up resources:\n","\n","# Try to open and write to a file that is not writable:\n","\n","#The try block will raise an error when trying to write to a read-only file:\n","\n","try:\n","  file = open(\"demo.txt\",\"r\")\n","  file.write(\"Lorum Ipsum\")\n","except:\n","  print(\"Something went wrong when writing to the file\")\n","\n","finally:\n","  file.close()\n","\n","#The program can continue, without leaving the file object open"],"execution_count":3,"outputs":[{"output_type":"stream","name":"stdout","text":["Something went wrong when writing to the file\n"]}]},{"cell_type":"code","source":["file = open(\"demo.txt\",\"w\")\n","file.write(\"Lorum Ipsum\")\n","\n","file.close()"],"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"PtdOVJjXg1SQ","executionInfo":{"status":"ok","timestamp":1752288325653,"user_tz":-330,"elapsed":22,"user":{"displayName":"udaysudheer","userId":"14541240013211259843"}},"outputId":"436c1383-05ff-4716-9d08-4193ebe7e016"},"execution_count":11,"outputs":[{"output_type":"stream","name":"stdout","text":["Lorum Ipsum\n"]}]}]}